"""Initial schema.

Revision ID: 0001
Revises:
Create Date: 2026-09-18

The baseline is created from the SQLAlchemy metadata rather than hand-written DDL, so
the first migration cannot drift from the models. Every change after this one is a
normal autogenerated revision.
"""
from __future__ import annotations

from alembic import op

from app.db.models import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
